; MiniImp LLVM IR generated by the Compilation Techniques project
source_filename = "miniimp"

define i64 @func(i64 %in) {
entry:
  %var0 = alloca i64 ; x
  %var1 = alloca i64 ; y

  store i64 %in, ptr %var0
  store i64 0, ptr %var1
  br label %block4

block0:
  %tmp0 = load i64, ptr %var1
  ret i64 %tmp0

block1:
  %tmp1 = load i64, ptr %var1
  %tmp2 = add i64 %tmp1, 8
  store i64 %tmp2, ptr %var1
  br label %block0

block2:
  %tmp3 = load i64, ptr %var1
  %tmp4 = sub i64 %tmp3, 2
  store i64 %tmp4, ptr %var1
  br label %block0

block3:
  %tmp5 = load i64, ptr %var1
  %tmp6 = icmp slt i64 %tmp5, 10
  br i1 %tmp6, label %block1, label %block2

block4:
  %tmp7 = load i64, ptr %var0
  store i64 %tmp7, ptr %var1
  br label %block3

}
