use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io;
use std::path::Path;

use super::ast::{AExpr, BExpr, Program};
use super::cfg::{ControlFlowGraph, OutgoingEdges, SimpleStatement, program_to_cfg};

/// Generates LLVM IR for a MiniImp program and writes it to `path`.
pub fn write_llvm_ir<P: AsRef<Path>>(program: &Program, path: P) -> io::Result<()> {
    fs::write(path, generate_llvm_ir(program))
}

/// Generates LLVM IR for a MiniImp program.
///
/// The initial IR deliberately uses stack slots (`alloca`, `load`, and
/// `store`). LLVM's `mem2reg` pass can then promote those slots to SSA
/// registers and insert the required phi nodes at control-flow joins and
/// loop headers.
pub fn generate_llvm_ir(program: &Program) -> String {
    let cfg = program_to_cfg(program);
    LlvmIrGenerator::new(&cfg).generate()
}

struct LlvmIrGenerator<'a> {
    cfg: &'a ControlFlowGraph,
    variable_slots: BTreeMap<String, String>,
    next_temporary: usize,
}

impl<'a> LlvmIrGenerator<'a> {
    fn new(cfg: &'a ControlFlowGraph) -> Self {
        let variables = collect_cfg_variables(cfg);

        let variable_slots = variables
            .into_iter()
            .enumerate()
            .map(|(index, variable)| (variable, format!("%var{}", index)))
            .collect();

        Self {
            cfg,
            variable_slots,
            next_temporary: 0,
        }
    }

    fn generate(mut self) -> String {
        let mut ir = String::new();

        ir.push_str("; MiniImp LLVM IR generated by the Compilation Techniques project\n");

        ir.push_str("source_filename = \"miniimp\"\n\n");
        ir.push_str("define i64 @func(i64 %in) {\n");
        ir.push_str("entry:\n");

        /*
         * All allocas are placed in the LLVM entry block.
         * This is required for the standard mem2reg promotion pass.
         */
        for (variable, slot) in &self.variable_slots {
            ir.push_str(&format!("  {} = alloca i64 ; {}\n", slot, variable));
        }

        ir.push('\n');

        /*
         * The program input receives the function argument.
         * Other variables are initialized to zero as a defensive
         * backend default.
         *
         * Source programs are still expected to pass the
         * undefined-variable check before code generation.
         */
        for (variable, slot) in &self.variable_slots {
            if variable == &self.cfg.input {
                ir.push_str(&format!("  store i64 %in, ptr {}\n", slot));
            } else {
                ir.push_str(&format!("  store i64 0, ptr {}\n", slot));
            }
        }

        ir.push_str(&format!("  br label %block{}\n\n", self.cfg.entry));

        /*
         * Clone the block vector so that temporary-name generation
         * can mutate the generator while translating each block.
         */
        let blocks = self.cfg.blocks().to_vec();

        for block in blocks {
            ir.push_str(&format!("block{}:\n", block.id));

            let branch_condition = match &block.statement {
                SimpleStatement::Skip => None,

                SimpleStatement::Assign(variable, expression) => {
                    let value = self.generate_aexpr(expression, &mut ir);

                    let slot = self.variable_slot(variable);

                    ir.push_str(&format!("  store i64 {}, ptr {}\n", value, slot));

                    None
                }

                SimpleStatement::Guard(condition) => Some(self.generate_bexpr(condition, &mut ir)),
            };

            match &block.outgoing {
                OutgoingEdges::End => {
                    let output_slot = self.variable_slot(&self.cfg.output).to_string();

                    let result = self.fresh_temporary();

                    ir.push_str(&format!("  {} = load i64, ptr {}\n", result, output_slot));

                    ir.push_str(&format!("  ret i64 {}\n", result));
                }

                OutgoingEdges::Goto(next) => {
                    ir.push_str(&format!("  br label %block{}\n", next));
                }

                OutgoingEdges::Branch { on_true, on_false } => {
                    let condition = branch_condition.expect(
                        "a CFG block with Branch edges must contain \
                         a guard statement",
                    );

                    ir.push_str(&format!(
                        "  br i1 {}, label %block{}, label %block{}\n",
                        condition, on_true, on_false
                    ));
                }
            }

            ir.push('\n');
        }

        ir.push_str("}\n");

        ir
    }

    fn generate_aexpr(&mut self, expression: &AExpr, ir: &mut String) -> String {
        match expression {
            AExpr::Var(variable) => {
                let slot = self.variable_slot(variable).to_string();

                let result = self.fresh_temporary();

                ir.push_str(&format!("  {} = load i64, ptr {}\n", result, slot));

                result
            }

            AExpr::Int(value) => value.to_string(),

            AExpr::Add(left, right) => self.generate_binary_aexpr("add", left, right, ir),

            AExpr::Sub(left, right) => self.generate_binary_aexpr("sub", left, right, ir),

            AExpr::Mul(left, right) => self.generate_binary_aexpr("mul", left, right, ir),
        }
    }

    fn generate_binary_aexpr(
        &mut self,
        instruction: &str,
        left: &AExpr,
        right: &AExpr,
        ir: &mut String,
    ) -> String {
        let left_value = self.generate_aexpr(left, ir);
        let right_value = self.generate_aexpr(right, ir);
        let result = self.fresh_temporary();

        ir.push_str(&format!(
            "  {} = {} i64 {}, {}\n",
            result, instruction, left_value, right_value
        ));

        result
    }

    fn generate_bexpr(&mut self, expression: &BExpr, ir: &mut String) -> String {
        match expression {
            BExpr::True => "true".to_string(),

            BExpr::False => "false".to_string(),

            BExpr::And(left, right) => {
                let left_value = self.generate_bexpr(left, ir);

                let right_value = self.generate_bexpr(right, ir);

                let result = self.fresh_temporary();

                ir.push_str(&format!(
                    "  {} = and i1 {}, {}\n",
                    result, left_value, right_value
                ));

                result
            }

            BExpr::Not(value) => {
                let value = self.generate_bexpr(value, ir);

                let result = self.fresh_temporary();

                ir.push_str(&format!("  {} = xor i1 {}, true\n", result, value));

                result
            }

            BExpr::Less(left, right) => {
                let left_value = self.generate_aexpr(left, ir);

                let right_value = self.generate_aexpr(right, ir);

                let result = self.fresh_temporary();

                ir.push_str(&format!(
                    "  {} = icmp slt i64 {}, {}\n",
                    result, left_value, right_value
                ));

                result
            }
        }
    }

    fn variable_slot(&self, variable: &str) -> &str {
        self.variable_slots
            .get(variable)
            .map(String::as_str)
            .unwrap_or_else(|| {
                panic!(
                    "missing LLVM stack slot for variable \
                     '{variable}'"
                )
            })
    }

    fn fresh_temporary(&mut self) -> String {
        let name = format!("%tmp{}", self.next_temporary);

        self.next_temporary += 1;

        name
    }
}

fn collect_cfg_variables(cfg: &ControlFlowGraph) -> BTreeSet<String> {
    let mut variables = BTreeSet::new();

    variables.insert(cfg.input.clone());
    variables.insert(cfg.output.clone());

    for block in cfg.blocks() {
        match &block.statement {
            SimpleStatement::Skip => {}

            SimpleStatement::Assign(variable, expression) => {
                variables.insert(variable.clone());

                collect_aexpr_variables(expression, &mut variables);
            }

            SimpleStatement::Guard(condition) => {
                collect_bexpr_variables(condition, &mut variables);
            }
        }
    }

    variables
}

fn collect_aexpr_variables(expression: &AExpr, variables: &mut BTreeSet<String>) {
    match expression {
        AExpr::Var(variable) => {
            variables.insert(variable.clone());
        }

        AExpr::Int(_) => {}

        AExpr::Add(left, right) | AExpr::Sub(left, right) | AExpr::Mul(left, right) => {
            collect_aexpr_variables(left, variables);
            collect_aexpr_variables(right, variables);
        }
    }
}

fn collect_bexpr_variables(expression: &BExpr, variables: &mut BTreeSet<String>) {
    match expression {
        BExpr::True | BExpr::False => {}

        BExpr::And(left, right) => {
            collect_bexpr_variables(left, variables);
            collect_bexpr_variables(right, variables);
        }

        BExpr::Not(value) => {
            collect_bexpr_variables(value, variables);
        }

        BExpr::Less(left, right) => {
            collect_aexpr_variables(left, variables);
            collect_aexpr_variables(right, variables);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::generate_llvm_ir;

    use crate::miniimp::ast::{AExpr, BExpr, Command, Program};

    #[test]
    fn generates_stack_based_llvm_ir() {
        let program = Program {
            input: "x".to_string(),
            output: "y".to_string(),

            body: Command::Assign(
                "y".to_string(),
                AExpr::Add(
                    Box::new(AExpr::Var("x".to_string())),
                    Box::new(AExpr::Int(1)),
                ),
            ),
        };

        let ir = generate_llvm_ir(&program);

        assert!(ir.contains("define i64 @func(i64 %in)"));

        assert!(ir.contains("alloca i64"));
        assert!(ir.contains("load i64"));
        assert!(ir.contains("add i64"));
        assert!(ir.contains("store i64"));
        assert!(ir.contains("ret i64"));
    }

    #[test]
    fn generates_conditional_branches() {
        let program = Program {
            input: "x".to_string(),
            output: "y".to_string(),

            body: Command::If(
                BExpr::Less(
                    Box::new(AExpr::Var("x".to_string())),
                    Box::new(AExpr::Int(10)),
                ),
                Box::new(Command::Assign("y".to_string(), AExpr::Int(1))),
                Box::new(Command::Assign("y".to_string(), AExpr::Int(2))),
            ),
        };

        let ir = generate_llvm_ir(&program);

        assert!(ir.contains("icmp slt i64"));
        assert!(ir.contains("br i1"));
        assert!(ir.contains("label %block"));
    }

    #[test]
    fn generates_loop_back_edges() {
        let program = Program {
            input: "x".to_string(),
            output: "x".to_string(),

            body: Command::While(
                BExpr::Less(
                    Box::new(AExpr::Var("x".to_string())),
                    Box::new(AExpr::Int(3)),
                ),
                Box::new(Command::Assign(
                    "x".to_string(),
                    AExpr::Add(
                        Box::new(AExpr::Var("x".to_string())),
                        Box::new(AExpr::Int(1)),
                    ),
                )),
            ),
        };

        let ir = generate_llvm_ir(&program);

        assert!(ir.matches("br label %block").count() >= 2);

        assert!(ir.contains("br i1"));
    }
}
